-- Legacy telemetry columns used zero as a database default. Rebuild the SQLite
-- table so unknown values are NULL; websocket samples retain explicit zeroes.
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_devices" (
 "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "label" TEXT NOT NULL, "friendly_id" TEXT, "device_type" TEXT NOT NULL DEFAULT 'trmnl', "transport" TEXT NOT NULL DEFAULT 'pull', "external_id" TEXT, "capabilities" JSONB, "configuration" JSONB, "telemetry" JSONB, "profile_id" TEXT NOT NULL, "capabilities_override" JSONB, "delivery_policy_id" TEXT NOT NULL, "mac_address" TEXT, "api_key" TEXT, "last_connected_at" DATETIME, "presentation_revision" INTEGER NOT NULL DEFAULT 0, "firmware_version" TEXT, "model_id" INTEGER, "playlist_id" INTEGER, "is_active" BOOLEAN NOT NULL DEFAULT true, "wifi" INTEGER, "battery" REAL, "refresh_rate" INTEGER NOT NULL DEFAULT 900, "image_timeout" INTEGER NOT NULL DEFAULT 0, "width" INTEGER NOT NULL DEFAULT 0, "height" INTEGER NOT NULL DEFAULT 0, "proxy" BOOLEAN NOT NULL DEFAULT false, "firmware_update" BOOLEAN NOT NULL DEFAULT true, "sleep_start_at" TEXT, "sleep_stop_at" TEXT, "show_sleep_screen" BOOLEAN NOT NULL DEFAULT false, "last_seen_at" DATETIME, "refresh_pending" BOOLEAN NOT NULL DEFAULT false, "last_screen_id" TEXT, "screen_started_at" DATETIME, "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updated_at" DATETIME NOT NULL,
 CONSTRAINT "devices_model_id_fkey" FOREIGN KEY ("model_id") REFERENCES "models" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "devices_playlist_id_fkey" FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("id") ON DELETE SET NULL ON UPDATE CASCADE, CONSTRAINT "devices_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "device_profiles" ("profile_id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "devices_delivery_policy_id_fkey" FOREIGN KEY ("delivery_policy_id") REFERENCES "delivery_policies" ("policy_id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "devices_capabilities_override_json" CHECK ("capabilities_override" IS NULL OR json_valid("capabilities_override")), CONSTRAINT "devices_capabilities_override_identity" CHECK ("capabilities_override" IS NULL OR (json_type("capabilities_override", '$.profileId') IS NULL AND json_type("capabilities_override", '$.protocolVersion') IS NULL))
);
INSERT INTO "new_devices" SELECT "id", "label", "friendly_id", "device_type", "transport", "external_id", "capabilities", "configuration", "telemetry", "profile_id", "capabilities_override", "delivery_policy_id", "mac_address", "api_key", "last_connected_at", "presentation_revision", "firmware_version", "model_id", "playlist_id", "is_active", CASE WHEN "wifi" = 0 AND json_extract("telemetry", '$.websocket.rssi') IS NULL THEN NULL ELSE "wifi" END, CASE WHEN "battery" = 0 AND json_extract("telemetry", '$.websocket.batteryPercent') IS NULL THEN NULL ELSE "battery" END, "refresh_rate", "image_timeout", "width", "height", "proxy", "firmware_update", "sleep_start_at", "sleep_stop_at", "show_sleep_screen", "last_seen_at", "refresh_pending", "last_screen_id", "screen_started_at", "created_at", "updated_at" FROM "devices";
DROP TABLE "devices";
ALTER TABLE "new_devices" RENAME TO "devices";
CREATE UNIQUE INDEX "devices_external_id_key" ON "devices"("external_id");
CREATE UNIQUE INDEX "devices_mac_address_key" ON "devices"("mac_address");
CREATE UNIQUE INDEX "devices_api_key_key" ON "devices"("api_key");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
